# Generated by Django 5.2.8 on 2025-11-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cor_fundo', models.CharField(max_length=7)),
                ('cor_texto', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('link_repositorio', models.URLField()),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='projetos/')),
                ('tecnologias', models.ManyToManyField(to='portifolio.tecnologia')),
            ],
        ),
    ]
